Fail if any check fails

diff --git a/.git_template/hooks/pre-commit b/.git_template/hooks/pre-commit
--- a/.git_template/hooks/pre-commit
+++ b/.git_template/hooks/pre-commit
@@ -20,4 +20,12 @@ if [[ -f Cargo.toml ]]; then
   fi
 fi
 
+check
+exit_code=$?
+
+if [ $exit_code -ne 0 ]; then
+    echo "❌ Commit blocked: Failed checks"
+    exit 1
+fi
+
 ~/.git_template/hooks/run-local-hook pre-commit
